410I Assignment 3

Question 1
a) To find the terms of the net flux equation we need to find the view factors, using the configuration factors sheet number 17


In [72]:
import numpy as np
import planck as p
import radiosity as r

h=1.6
r1 = 1
r2 = 0.3

a1 = 4*np.pi*r1**2
a2 = np.pi*r2**2
a3 = 2*np.pi*r1*(h+2*r1)-a2

f11 = 0
f12 = .5*(1-1/(np.sqrt(1+(.3/h)**2)))
f13 = 1-f12
f21 = a1/a2*f12
f22 = 0
f23 = 1-f21
f31 = a1/a3*f13
f32 = a2/a3*f23
f33 = 1-f31-f32

a = np.array([a1, a2, a3])
f = np.array([[f11, f12, f13], [f21, f22, f23], [f31, f32, f33]])
T = np.array([8000, 400, 0])
eps  = np.array([0.9, 0.3, 1])
print(f)
print(a)


qr = r.rad_encl_q(f,T,eps)*a
for i in range(qr.size):
    print ('Incident energy on surface {:1} = {:.4} W'.format(i+1,qr[i])) 



[[0.         0.00856391 0.99143609]
 [0.38061807 0.         0.61938193]
 [0.55776995 0.00784028 0.43438977]]
[12.56637061  0.28274334 22.33672377]
Incident energy on surface 1 = 869.9 W
Incident energy on surface 2 = -3.056 W
Incident energy on surface 3 = -866.9 W


Now calculate flux leaving 2

In [71]:
energy = 0.3*5.67e-8*400**4*a2

print(energy)

123.12228335054373
